[package]
name = "openapi-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
aide = "0.13.4"
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
fs-err = "3.0.0"
serde_json = "1.0.133"
