[package]
name = "openapi-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
aide = "0.13.4"
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
fs-err = "3.0.0"
heck = "0.5.0"
indexmap = "2.7.0"
minijinja = "2.5.0"
schemars = "0.8.21"
serde = "1.0.215"
serde_json = "1.0.133"
tempfile = "3.14.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
